### ISSUE TITLE
Cannot find any contents on txt files on MyItems.py

### ISSUE THREAD

**Issue by John0731** [John0731/MyPython#2]
Please choose : 7
Please input your txt file path:D:\Test1\123.txt
What content you want to find on txt file?DDD

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\工作资料\MyItem\MyItems.py", line 379, in <module>
    MainFunction()
  File "C:\Users\Administrator\Desktop\工作资料\MyItem\MyItems.py", line 70, in MainFunction
    FindContent(Path,Content)
UnboundLocalError: local variable 'FindContent' referenced before assignment
======================================================

This bug occured on function: 7. Find Contents on txt files
Failed cases:
Test Case 029
Test Case 031
Test Case 032

**Comment by John0731** [comment]
Fixed by sumbited:4493ee6
